{% set name = "proglog" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 361ee074721c277b89b75c061336cb8c5f287c92b043efa562ccf7866cda931c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - tqdm

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - proglog

about:
  home: https://github.com/Edinburgh-Genome-Foundry/Proglog
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Logs and progress bars manager for Python

  description: |
    Proglog is a progress logging system for Python. It allows to build
    complex libraries while giving your users control over logs, callbacks
    and progress bars.
  dev_url: https://github.com/Edinburgh-Genome-Foundry/Proglog

extra:
  recipe-maintainers:
    - mdraw
